# RouteParams.yaml
# Defines the ros parameters which are required by the Route package

# String: The path to the database containing any route files for use in testing and demonstration.
# If the path starts with a "/" then it is treated as absolute otherwise it should be relative to the package path
default_database_path: '/opt/carma/routes/'

# Integer: The number of left route alerts which must be handled before
# the RouteManager node will notify the rest of the platform via a system alert
required_left_route_count: 3

# String: The id of the frame which represents an Earth Centered Earth Fixed (ECEF) frame
earth_frame_id: 'earth'

# String: The id of the frame which represents the bounding box center of the host vehicle
host_vehicle_frame_id: 'host_vehicle'
