# InterfaceMgrParams.yaml
# Defines the ros parameters that are required by the InterfaceMgr node

# Integer: the number of seconds to wait for driver discovery before declaring the system operational
driver_wait_time: 20

# Integer: The number of ms in which a controller must send a robot_status update for interface manager to consider it still active
# Units: ms
controller_status_timeout: 1000
